apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/crawler-python
  creationTimestamp: null
  name: crawler-python.apps.local.20250111.707.40698
spec:
  refName: crawler-python.apps.local
  releasedAt: "2025-01-11T07:08:59Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor-dev.buildservice.dev/ci/containerapp-crawler-python@sha256:d892e2bed6a7de9903e5d6fdbbc7a37323d6127bc1312907aafbe269dce90eb9
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250111.707.40698
