apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/search-proc
  creationTimestamp: null
  name: search-proc.apps.local.20240821.2011.33066
spec:
  refName: search-proc.apps.local
  releasedAt: "2024-08-21T20:16:44Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:9e72ed9d10c083c76221037308f674d3cfec0d0b37def8da0b4b3e9e8104061e
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2011.33066
