apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/search-proc
  creationTimestamp: null
  name: search-proc.apps.local.20240821.2010.12110
spec:
  refName: search-proc.apps.local
  releasedAt: "2024-08-21T20:15:52Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:094e5e0ae8dc42aca03aae2ec47e41738202bb43e40612f1c467f99baf0b3444
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2010.12110
