apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/search-proc
  creationTimestamp: null
  name: search-proc.apps.local.20240821.2010.31649
spec:
  refName: search-proc.apps.local
  releasedAt: "2024-08-21T20:16:44Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:71203b7bdd0749b83cb8591fe38c654ea1427abb130325e6ebcf45c10250015a
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2010.31649
