apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/search-proc
  creationTimestamp: null
  name: search-proc.apps.local.20240821.2009.21193
spec:
  refName: search-proc.apps.local
  releasedAt: "2024-08-21T20:13:57Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:6448f6e823244f27fb29c3553387e10443b029e501af44e08842fd72fea570aa
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2009.21193
