apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/crawler-python
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: crawler-python
spec:
  content:
    buildTimestamp: "2024-09-18T20:52:13Z"
    packageImage: supply-chain-docker-dev-local.usw1.packages.broadcom.com/ci/internal/tp-supplychain-local/build@sha256:cece5375a990e1fcc00dee464444cae45a0e34e84ba4315ba06bba78b9ee39bc
    packageRefName: crawler-python.apps.local
    packageVersion: 20240918.2052.13330
    summary: image:28324bb @ 2024-09-18T20:52:13Z
    version: 20240918.2052.13330
  health:
    maxUnavailableReplicas: 10%
  image: supply-chain-docker-dev-local.usw1.packages.broadcom.com/ci/internal/tp-supplychain-local/build@sha256:28324bb6d319f8462d291e9e11ababbedfc8604e80e144204fecc9d41161c498
  ports:
  - name: main
    port: 8080
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=crawler-python
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: crawler-python
  - for: kubernetes.service-target
    kind: Service
    name: crawler-python
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: crawler-python-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: crawler-python-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: crawler-python-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: crawler-python
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: crawler-python.apps.local.20240918.2052.13330
  - for: kubernetes.delete
    kind: Secret
    name: crawler-python-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: crawler-python-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: crawler-python-values
  resources:
    cpu: 300m
    memory: 1Gi
