apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/single-image-single-app
  creationTimestamp: null
  name: single-image-single-app.apps.local.20240723.1714.51756
spec:
  refName: single-image-single-app.apps.local
  releasedAt: "2024-07-23T17:16:13Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/supplychain/tanzu-build-images@sha256:84f8f3b51ef96572db26d9e5924b22c6f3599008a36678ad034dae996da76196
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240723.1714.51756
