apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/ui
  creationTimestamp: null
  name: ui.apps.local.20240821.2012.14385
spec:
  refName: ui.apps.local
  releasedAt: "2024-08-21T20:19:59Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:b2a2f5a89d6edfacfc0bb56af94752d65d651045595f1ae3e3785f27b6ded9d5
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2012.14385
