apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/ui
  creationTimestamp: null
  name: ui.apps.local.20240821.2009.36926
spec:
  refName: ui.apps.local
  releasedAt: "2024-08-21T20:17:05Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:2539c6d99aa4dc4af793347f035cb2f4a71476205b29fd2e92d4d509e27778cc
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2009.36926
