apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/availability
  creationTimestamp: null
  name: availability.apps.local.20240821.2009.36881
spec:
  refName: availability.apps.local
  releasedAt: "2024-08-21T20:12:12Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:5c5fc767e094c13633ff410d3ab8c20336311b7ca7f6c3412d4cdc3abbb8cdce
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2009.36881
