apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/availability
  creationTimestamp: null
  name: availability.apps.local.20240725.1704.42466
spec:
  refName: availability.apps.local
  releasedAt: "2024-07-25T17:07:05Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/supplychain/tanzu-build-images@sha256:02c329f89d1f1b81f93885780cadbca479e7b733f67bf11b252a09d20dd45d8f
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240725.1704.42466
