apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/availability
  creationTimestamp: null
  name: availability.apps.local.20240821.1943.31329
spec:
  refName: availability.apps.local
  releasedAt: "2024-08-21T19:45:26Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:2853c4e1d1bec468d592b904704a5831821216dfed25f1390c019cf1858b75d0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.1943.31329
