apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/availability
  creationTimestamp: null
  name: availability.apps.local.20240821.2007.48908
spec:
  refName: availability.apps.local
  releasedAt: "2024-08-21T20:09:55Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:0dff324ea1de4eaebf3242e9cb7772e5cfbe7414b8a5d79175e1d0f0dfc898b3
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2007.48908
