apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/api-gateway
  creationTimestamp: null
  name: api-gateway.apps.local.20240821.2010.50146
spec:
  refName: api-gateway.apps.local
  releasedAt: "2024-08-21T20:13:36Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:1909aa31c3b39d5166ec0ce518b1f0a61389d8dbeee1d5b322e4adbd7d0b30a4
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2010.50146
