apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/api-gateway
  creationTimestamp: null
  name: api-gateway.apps.local.20240725.1516.507
spec:
  refName: api-gateway.apps.local
  releasedAt: "2024-07-25T15:17:52Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/supplychain/tanzu-build-images@sha256:03ea0b3789fb9ba3c097c311d3783b2266efa7509c4b3a88a01d822c190f121f
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240725.1516.507
