apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/api-gateway
  creationTimestamp: null
  name: api-gateway.apps.local.20240821.2011.33066
spec:
  refName: api-gateway.apps.local
  releasedAt: "2024-08-21T20:13:57Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:cb5fb215852da2f574d94d6670f7b89a53aac1d471e8c79ae4af0f5b0d989b5e
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2011.33066
