apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/api-gateway
  creationTimestamp: null
  name: api-gateway.apps.local.20240821.1943.52677
spec:
  refName: api-gateway.apps.local
  releasedAt: "2024-08-21T19:45:19Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:992fa4d0b44cf7550983c53a8239c2ad9f627718cbfe4dd73c619797fc2ab11d
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.1943.52677
