apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/crawler-python
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: crawler-python
spec:
  content:
    buildTimestamp: "2025-01-14T18:40:31Z"
    gitCommit: 7893ceca4af1d04e2aa695c17e91c65a4d714cc0
    gitRef: sc-testing
    gitURL: github.com/atmandhol/tanzu-build-samples.git
    packageImage: harbor-dev.buildservice.dev/ci/containerapp-crawler-python@sha256:24f7b1bef4c939d1f3e1f2dcb63cbb3f517dff0c3e0a7e4c223502d9cff3576b
    packageRefName: crawler-python.apps.local
    packageVersion: 20250114.1840.31261
    summary: git:7893cec @ 2025-01-14T18:40:31Z
    version: 20250114.1840.31261
  health:
    maxUnavailableReplicas: 10%
  image: harbor-dev.buildservice.dev/ci/containerapp-crawler-python:20250114.1840.31261@sha256:d1c731df07259d61706d2540aba08da96da8762b079d94169a05e3240340db67
  ports:
  - name: main
    port: 8080
    protocol: HTTP
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=crawler-python
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: crawler-python
  - for: kubernetes.service-target
    kind: Service
    name: crawler-python
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: crawler-python-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: crawler-python-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: crawler-python-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: crawler-python
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: crawler-python.apps.local.20250114.1840.31261
  - for: kubernetes.delete
    kind: Secret
    name: crawler-python-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: crawler-python-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: crawler-python-values
  resources:
    cpu: 300m
    memory: 1Gi
