apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/crawler-python
  creationTimestamp: null
  name: crawler-python.apps.local.20250104.1121.34969
spec:
  refName: crawler-python.apps.local
  releasedAt: "2025-01-04T11:22:47Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor-dev.buildservice.dev/ci/containerapp-crawler-python@sha256:fbee11234d67fb9bf3b5916b6822f08d42acd828b4cab29b6765445e08c7c027
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250104.1121.34969
