apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/crawler-python
  creationTimestamp: null
  name: crawler-python.apps.local.20250224.1808.15180
spec:
  refName: crawler-python.apps.local
  releasedAt: "2025-02-24T18:14:17Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor-dev.buildservice.dev/ci/containerapp-crawler-python@sha256:af76e5f7dc1b4562380852fef45e8d2a580e31ddc39f81dce88006f522554555
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250224.1808.15180
