apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/crawler-python
  creationTimestamp: null
  name: crawler-python.apps.local.20250130.801.23936
spec:
  refName: crawler-python.apps.local
  releasedAt: "2025-01-30T08:02:14Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor-dev.buildservice.dev/ci/containerapp-crawler-python@sha256:f4e9c3ce1df8cc39dcf7e1a916c9f5b73fb6bcf9192777bf25348adb44d8ce8b
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250130.801.23936
