# tinker package
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/crawler-python
  creationTimestamp: null
  name: crawler-python.apps.local.20250116.2319.51956
spec:
  refName: crawler-python.apps.local
  releasedAt: "2025-01-16T23:20:52Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor-dev.buildservice.dev/ci/containerapp-crawler-python@sha256:dcc274aaf16edfba5f33875d64e859995584744f103fa6e488b1139b821392e4
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250116.2319.51956
