apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/search
  creationTimestamp: null
  name: search.apps.local.20240725.1704.42466
spec:
  refName: search.apps.local
  releasedAt: "2024-07-25T17:09:50Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/supplychain/tanzu-build-images@sha256:05f9e4e6fe0f69431268273bd3f283ce59c76645a9c180752b8f68182bb049aa
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240725.1704.42466
