apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/single-image-single-app
  creationTimestamp: null
  name: single-image-single-app.apps.local.20240725.1408.39284
spec:
  refName: single-image-single-app.apps.local
  releasedAt: "2024-07-25T14:10:07Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/supplychain/tanzu-build-images@sha256:549ee308039b2502212289f2858921e71def90fd043785d671e6a14bef29bd14
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240725.1408.39284
